
export const HANDLE_INCREMENT = "HANDLE_INCREMENT"
export const HANDLE_DECREMENT = "HANDLE_DECREMENT"
export const DELETE_ITEM = "DELETE_ITEM"
export const USER_LOGOUT = "USER_LOGOUT"
export const CLEAR_ITEM = "CLEAR_ITEM"

